### ISSUE TITLE
Feature request: a faster base::tcrossprod

### ISSUE THREAD

**Issue by aljabadi** [cran/Rfast#4]
`mat.mult` is much faster than `base::crossprod`. It would be nice to have a `tcrossprod` equivalent so one doesn't have to inefficiently do `mat.mult(x, t(y))` as for large matrices `t()` can be quite inefficient and a bottleneck for `mat.mult`.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the DESCRIPTION file. Thanks!
